.PHONY: clean All

All:
	@echo "----------Building project:[ proj3 - Debug ]----------"
	@cd "proj3" && "$(MAKE)" -f  "proj3.mk"
clean:
	@echo "----------Cleaning project:[ proj3 - Debug ]----------"
	@cd "proj3" && "$(MAKE)" -f  "proj3.mk" clean
